# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-05 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20170305_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'Liked'), ('d', 'Disliked'), ('u', 'Undecided')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together=set([('name', 'breed', 'age', 'gender')]),
        ),
    ]
